dist: trusty
sudo: true
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
 # - '9'
  - '8'
 # - '6'

script: travis_wait 30 npm test

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: "10 x64"
      before_deploy:
        - git config --global user.email "ichulinda@gmail.com"
        - git config --global user.name "Igmat (Travis CI)"
        - git remote set-url origin https://${GH_TOKEN}@github.com/Igmat/metaf.git > /dev/null 2>&1
        - git checkout master
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release

