# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr:
- master

jobs:
- template: configs/build-job.yml
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: configs/build-job.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'ubuntu-16.04'

- template: configs/build-job.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'
