import { SVGProps } from './SVGAttributes';

const svgNamespace = {
    animate: undefined,
    circle: undefined,
    clipPath: undefined,
    defs: undefined,
    desc: undefined,
    ellipse: undefined,
    feBlend: undefined,
    feColorMatrix: undefined,
    feComponentTransfer: undefined,
    feComposite: undefined,
    feConvolveMatrix: undefined,
    feDiffuseLighting: undefined,
    feDisplacementMap: undefined,
    feDistantLight: undefined,
    feDropShadow: undefined,
    feFlood: undefined,
    feFuncA: undefined,
    feFuncB: undefined,
    feFuncG: undefined,
    feFuncR: undefined,
    feGaussianBlur: undefined,
    feImage: undefined,
    feMerge: undefined,
    feMergeNode: undefined,
    feMorphology: undefined,
    feOffset: undefined,
    fePointLight: undefined,
    feSpecularLighting: undefined,
    feSpotLight: undefined,
    feTile: undefined,
    feTurbulence: undefined,
    filter: undefined,
    foreignObject: undefined,
    g: undefined,
    image: undefined,
    line: undefined,
    linearGradient: undefined,
    marker: undefined,
    mask: undefined,
    metadata: undefined,
    path: undefined,
    pattern: undefined,
    polygon: undefined,
    polyline: undefined,
    radialGradient: undefined,
    rect: undefined,
    stop: undefined,
    svg: undefined,
    switch: undefined,
    symbol: undefined,
    text: undefined,
    textPath: undefined,
    tspan: undefined,
    use: undefined,
    view: undefined,
};
export const svgTags = Object.keys(svgNamespace);
export type MetaFSVG = {
    [index in keyof typeof svgNamespace]: SVGProps;
};
