parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_v10:
        node_version: 10.x
      node_v12:
        node_version: 12.x
      node_v14:
        node_version: 14.x
      node_v16:
        node_version: 16.x
    maxParallel: 4

  steps:
  - template: build-steps.yml
    parameters:
      node_version: $(node_version)

  - script: npm run test:ci
    displayName: 'Test'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: 'tests/tap.xml'
